/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.pravejos.easycli;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class ArgumentParserTest {
  @Test
  void testParse() {
    // ARRANGE
    String[] args = new String[] {"-l", "101", "-s", "changed", "--myString2", "changed2", "11"};

    // ACT
    TestOption testOption = ArgumentParser.parse(TestOption.class, args);

    // ASSERT
    assertNotNull(testOption);
    assertEquals(101, testOption.getLongWithDefault());
    assertEquals("changed", testOption.getStringWithDefault());
    assertEquals("changed2", testOption.getString2());
    assertEquals(11, testOption.getIntParamWithDefault());
  }
}
